data<-read.table("C:\\household_power_consumption.txt", header=T, sep=';', na.strings="?", check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data$Date<-as.Date(data$Date, format="%d/%m/%Y")
data_sub<- subset(data, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
hist(data_sub$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
dev.copy(png, file="C:\\plot1.png", height=480, width=480)
dev.off()
